
platform :ios, '8.0'
inhibit_all_warnings!

def shared_pod
    pod "MJRefresh"
    pod "YYKit"
    pod "MJExtension"
    pod "AFNetworking"
    pod "Masonry"
    pod "SDWebImage"
    pod "SDCycleScrollView"
    pod "IQKeyboardManager"
    pod "DACircularProgress"
    pod "FLAnimatedImage"
    pod 'TYAttributedLabel', '~> 2.6.2'
end

target 'RuiHaoTalents' do
    shared_pod
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
